# Generated by Django 6.1 on 2026-09-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountinvitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountinvitation',
            options={'ordering': ('-invited_at',), 'verbose_name': 'アカウント招待', 'verbose_name_plural': 'アカウント招待'},
        ),
    ]
