# Generated by Django 6.1 on 2026-09-04 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='会社メールアドレス')),
                ('display_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('department', models.CharField(choices=[('sales', '営業部'), ('general_affairs', '総務部'), ('system', 'システム部')], max_length=20, verbose_name='部署')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='招待日時')),
                ('accepted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='利用開始日時')),
                ('user', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_invitation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
