# Generated by Django 6.1 on 2026-09-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_requests', '0007_remove_approvedapplication_source_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedapplication',
            name='entered_by_email',
            field=models.EmailField(blank=True, editable=False, max_length=254, verbose_name='登録責任者メールアドレス'),
        ),
        migrations.AddField(
            model_name='approvedapplication',
            name='entered_by_name',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='登録責任者氏名'),
        ),
    ]
