# Generated by Django 6.1 on 2026-09-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_requests', '0008_approvedapplication_entered_by_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvedapplication',
            options={'ordering': ['-created_at'], 'verbose_name': '資産台帳登録', 'verbose_name_plural': '資産台帳登録'},
        ),
        migrations.AlterField(
            model_name='approvedapplication',
            name='application_type',
            field=models.CharField(choices=[('pc', 'PC貸出'), ('memory', '外部記憶装置貸出'), ('lan', 'LAN機器貸出'), ('phone', 'スマートフォン購入'), ('other', 'その他')], db_index=True, max_length=20, verbose_name='機器種別'),
        ),
    ]
