# Generated by Django 6.1 on 2026-09-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_requests', '0009_alter_approvedapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedapplication',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='対象者氏名'),
        ),
        migrations.AlterField(
            model_name='approvedapplication',
            name='approved_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='旧承認日'),
        ),
        migrations.AlterField(
            model_name='approvedapplication',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='所属部署'),
        ),
    ]
