"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'local-development-key-not-for-deployment',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]


# Account registration and recovery
#
# Registration is deliberately disabled when no company domain is configured.
# Example (PowerShell):
#   $env:COMPANY_EMAIL_DOMAINS = "example.co.jp"
COMPANY_EMAIL_DOMAINS = tuple(
    domain.strip().casefold()
    for domain in os.environ.get('COMPANY_EMAIL_DOMAINS', '').split(',')
    if domain.strip()
)
FRONTEND_BASE_URL = os.environ.get(
    'FRONTEND_BASE_URL',
    'http://127.0.0.1:5173',
).rstrip('/')
EMAIL_VERIFICATION_TIMEOUT = int(
    os.environ.get('EMAIL_VERIFICATION_TIMEOUT', '86400')
)
EMAIL_VERIFICATION_RESEND_COOLDOWN = int(
    os.environ.get('EMAIL_VERIFICATION_RESEND_COOLDOWN', '60')
)
PASSWORD_RESET_TIMEOUT = int(os.environ.get('PASSWORD_RESET_TIMEOUT', '3600'))
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    'Asset Desk <no-reply@example.invalid>',
)

# The application-level limits protect the development and single-process setup.
# Use a shared cache and an infrastructure-level limiter in a multi-process deployment.
AUTH_RATE_LIMITS = {
    'login': (10, 300),
    'register': (5, 3600),
    'email_verification': (20, 900),
    'email_resend': (3, 3600),
    'password_reset': (3, 3600),
    'password_reset_confirm': (10, 3600),
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'asset-desk-auth-rate-limits',
    },
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts.apps.AccountsConfig',
    'asset_requests.apps.AssetRequestsConfig',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILER_BACKEND = os.environ.get(
    'DJANGO_MAILER_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
MAILERS = {
    'default': {
        'BACKEND': MAILER_BACKEND,
    },
}

if MAILER_BACKEND == 'django.core.mail.backends.smtp.EmailBackend':
    MAILERS['default']['OPTIONS'] = {
        'host': os.environ['SMTP_HOST'],
        'port': int(os.environ.get('SMTP_PORT', '587')),
        'username': os.environ.get('SMTP_USERNAME', ''),
        'password': os.environ.get('SMTP_PASSWORD', ''),
        'use_tls': os.environ.get('SMTP_USE_TLS', 'true').casefold() == 'true',
        'use_ssl': os.environ.get('SMTP_USE_SSL', 'false').casefold() == 'true',
        'timeout': int(os.environ.get('SMTP_TIMEOUT', '10')),
    }
