# Generated by Django 6.1 on 2026-09-02 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalStorageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100, verbose_name='申請者氏名')),
                ('department', models.CharField(max_length=100, verbose_name='所属部署')),
                ('employee_number', models.CharField(db_index=True, max_length=50, verbose_name='社員番号')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認'), ('rejected', '却下')], db_index=True, default='pending', max_length=20, verbose_name='申請状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='申請日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='利用者氏名')),
                ('device_name', models.CharField(max_length=100, verbose_name='機器名')),
                ('capacity', models.CharField(max_length=50, verbose_name='容量')),
                ('location', models.CharField(max_length=200, verbose_name='利用場所')),
                ('loan_date', models.DateField(verbose_name='貸し出し日')),
            ],
            options={
                'verbose_name': '外部記憶装置貸出申請',
                'verbose_name_plural': '外部記憶装置貸出申請',
                'db_table': 'asset_requests_external_storage_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100, verbose_name='申請者氏名')),
                ('department', models.CharField(max_length=100, verbose_name='所属部署')),
                ('employee_number', models.CharField(db_index=True, max_length=50, verbose_name='社員番号')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認'), ('rejected', '却下')], db_index=True, default='pending', max_length=20, verbose_name='申請状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='申請日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='利用者氏名')),
                ('management_number', models.CharField(db_index=True, max_length=50, verbose_name='管理番号')),
                ('start_date', models.DateField(verbose_name='利用開始日')),
                ('location', models.CharField(max_length=200, verbose_name='利用場所')),
            ],
            options={
                'verbose_name': 'PC貸出申請',
                'verbose_name_plural': 'PC貸出申請',
                'db_table': 'asset_requests_pc_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LANRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100, verbose_name='申請者氏名')),
                ('department', models.CharField(max_length=100, verbose_name='所属部署')),
                ('employee_number', models.CharField(db_index=True, max_length=50, verbose_name='社員番号')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認'), ('rejected', '却下')], db_index=True, default='pending', max_length=20, verbose_name='申請状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='申請日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('device_type', models.CharField(choices=[('LANケーブル', 'LANケーブル'), ('USB-LANアダプター', 'USB-LANアダプター'), ('モバイルルーター', 'モバイルルーター'), ('その他', 'その他')], max_length=30, verbose_name='機器種別')),
                ('device_name', models.CharField(max_length=100, verbose_name='機器名')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='必要個数')),
                ('start_date', models.DateField(verbose_name='利用開始日')),
                ('return_date', models.DateField(verbose_name='返却予定日')),
                ('location', models.CharField(max_length=200, verbose_name='利用場所')),
                ('purpose', models.TextField(verbose_name='利用目的')),
                ('notes', models.TextField(blank=True, verbose_name='ケーブル長・備考')),
            ],
            options={
                'verbose_name': 'LAN機器貸出申請',
                'verbose_name_plural': 'LAN機器貸出申請',
                'db_table': 'asset_requests_lan_request',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='lan_quantity_at_least_one'), models.CheckConstraint(condition=models.Q(('return_date__gte', models.F('start_date'))), name='lan_return_date_on_or_after_start_date')],
            },
        ),
        migrations.CreateModel(
            name='SmartphoneRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100, verbose_name='申請者氏名')),
                ('department', models.CharField(max_length=100, verbose_name='所属部署')),
                ('employee_number', models.CharField(db_index=True, max_length=50, verbose_name='社員番号')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認'), ('rejected', '却下')], db_index=True, default='pending', max_length=20, verbose_name='申請状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='申請日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('os', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android'), ('指定なし', '指定なし')], max_length=20, verbose_name='OS')),
                ('line_type', models.CharField(choices=[('新規契約', '新規契約'), ('機種変更', '機種変更'), ('端末のみ購入', '端末のみ購入')], max_length=20, verbose_name='回線区分')),
                ('model_name', models.CharField(max_length=100, verbose_name='機種')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='台数')),
                ('purchase_date', models.DateField(verbose_name='購入日')),
                ('storage', models.CharField(choices=[('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('指定なし', '指定なし')], max_length=20, verbose_name='容量')),
                ('sim_required', models.BooleanField(verbose_name='SIMの有無')),
                ('purpose', models.TextField(verbose_name='利用目的')),
                ('notes', models.TextField(blank=True, verbose_name='希望キャリア・備考')),
            ],
            options={
                'verbose_name': 'スマートフォン購入申請',
                'verbose_name_plural': 'スマートフォン購入申請',
                'db_table': 'asset_requests_smartphone_request',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='smartphone_quantity_at_least_one')],
            },
        ),
    ]
