# Generated by Django 6.1 on 2026-09-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_requests', '0010_alter_approvedapplication_applicant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedapplication',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='申請者氏名'),
        ),
    ]
