# Generated by Django 6.1 on 2026-09-08 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_ledger_states(apps, schema_editor):
    State = apps.get_model("asset_requests", "ApprovedLedgerState")
    for application_type in ("pc", "memory", "lan", "phone", "other"):
        State.objects.using(schema_editor.connection.alias).get_or_create(application_type=application_type)
    # Existing records remain unchanged. Historical edits cannot be recovered,
    # so no invented create or update audit events are backfilled.


class Migration(migrations.Migration):

    dependencies = [
        ('asset_requests', '0013_move_disposal_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedLedgerState',
            fields=[
                ('application_type', models.CharField(choices=[('pc', 'PC貸出'), ('memory', '外部記憶装置貸出'), ('lan', 'LAN機器貸出'), ('phone', 'スマートフォン購入'), ('other', 'その他')], max_length=20, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('pending', 'Excel未反映'), ('synced', '反映済み'), ('error', '同期失敗')], default='pending', max_length=10)),
                ('generation', models.PositiveBigIntegerField(default=0)),
                ('synced_generation', models.PositiveBigIntegerField(default=0)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='approvedapplication',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='取消理由'),
        ),
        migrations.AddField(
            model_name='approvedapplication',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='取消済み'),
        ),
        migrations.AddField(
            model_name='approvedapplication',
            name='revision',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='版番号'),
        ),
        migrations.CreateModel(
            name='ApprovedApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=150)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('create', '登録'), ('update', '修正'), ('cancel', '取消'), ('restore', '復元')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('changes', models.JSONField(default=list)),
                ('reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='asset_requests.approvedapplication')),
            ],
            options={
                'verbose_name': '台帳の変更履歴',
                'verbose_name_plural': '台帳の変更履歴',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.RunPython(seed_ledger_states, migrations.RunPython.noop),
    ]
