# Generated by Django 5.2.17 on 2026-09-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalStorageLoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100, verbose_name='申請者情報の氏名')),
                ('department', models.CharField(max_length=100, verbose_name='所属部署')),
                ('employee_number', models.CharField(max_length=50, verbose_name='社員番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='貸出者氏名')),
                ('device_name', models.CharField(max_length=100, verbose_name='機器名')),
                ('capacity', models.CharField(max_length=50, verbose_name='容量')),
                ('location', models.CharField(max_length=200, verbose_name='場所')),
                ('loan_date', models.DateField(verbose_name='貸し出し日')),
            ],
            options={
                'verbose_name': '外部記憶装置貸出申請',
                'verbose_name_plural': '外部記憶装置貸出申請',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanEquipmentLoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100, verbose_name='申請者情報の氏名')),
                ('department', models.CharField(max_length=100, verbose_name='所属部署')),
                ('employee_number', models.CharField(max_length=50, verbose_name='社員番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('device_type', models.CharField(choices=[('LANケーブル', 'LANケーブル'), ('USB-LANアダプター', 'USB-LANアダプター'), ('モバイルルーター', 'モバイルルーター'), ('その他', 'その他')], max_length=30, verbose_name='機器種別')),
                ('device_name', models.CharField(max_length=100, verbose_name='機器名')),
                ('start_date', models.DateField(verbose_name='利用開始日')),
                ('return_date', models.DateField(verbose_name='返却予定日')),
                ('location', models.CharField(max_length=200, verbose_name='利用場所')),
            ],
            options={
                'verbose_name': 'LAN機器貸出申請',
                'verbose_name_plural': 'LAN機器貸出申請',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcLoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100, verbose_name='申請者情報の氏名')),
                ('department', models.CharField(max_length=100, verbose_name='所属部署')),
                ('employee_number', models.CharField(max_length=50, verbose_name='社員番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='貸出者氏名')),
                ('management_number', models.CharField(max_length=50, verbose_name='管理番号')),
                ('start_date', models.DateField(verbose_name='利用開始日')),
                ('location', models.CharField(max_length=200, verbose_name='利用場所')),
            ],
            options={
                'verbose_name': 'PC貸出申請',
                'verbose_name_plural': 'PC貸出申請',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmartphonePurchaseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100, verbose_name='申請者情報の氏名')),
                ('department', models.CharField(max_length=100, verbose_name='所属部署')),
                ('employee_number', models.CharField(max_length=50, verbose_name='社員番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('model_name', models.CharField(max_length=100, verbose_name='機種')),
                ('purchase_date', models.DateField(verbose_name='購入日')),
                ('storage', models.CharField(choices=[('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('指定なし', '指定なし')], max_length=10, verbose_name='容量')),
                ('sim_required', models.CharField(choices=[('あり', 'あり'), ('なし', 'なし')], max_length=2, verbose_name='SIMの有無')),
            ],
            options={
                'verbose_name': 'スマートフォン購入申請',
                'verbose_name_plural': 'スマートフォン購入申請',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
